---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aap26
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/lennysh/aap-openshift-argocd-gitops.git
    path: app-aap26
    targetRevision: HEAD
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: aap26
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    # syncOptions:
    #   - CreateNamespace=true
...
