---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: automation-orchestrator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lennysh/argocd-playground.git
    path: app-automation-orchestrator
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: automation-orchestrator
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: aap.ansible.com
      kind: AutomationOrchestrator
      jsonPointers:
        - /status
