---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: aap-opa
    argocd.argoproj.io/managed-by: openshift-gitops
  name: aap-opa
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  finalizers:
    - kubernetes
...
