---
apiVersion: v1
kind: Service
metadata:
  name: opa
  namespace: aap-opa
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: opa
    app.kubernetes.io/instance: cluster-configs
spec:
  type: ClusterIP
  selector:
    app: opa
  ports:
    - name: http
      protocol: TCP
      port: 8181
      targetPort: 8181
...
