---
apiVersion: v1
kind: Namespace
metadata:
  name: automation-orchestrator-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    kubernetes.io/metadata.name: automation-orchestrator-operator-system
    argocd.argoproj.io/managed-by: openshift-gitops
spec:
  finalizers:
    - kubernetes
