---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-devspaces
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    kubernetes.io/metadata.name: openshift-devspaces
    argocd.argoproj.io/managed-by: openshift-gitops
spec:
  finalizers:
    - kubernetes
...
